### ISSUE TITLE
Requests not showing at all

### ISSUE THREAD

**Issue by DamianSz2000** [Riotphobia/Netherblade#1] opened 2022-11-26 02:18 UTC
![image](https://user-images.githubusercontent.com/92025938/204068579-1e2de9b0-b972-4ad7-ab60-6f6ff44f9d27.png)
These are all requests that i got. I am going through client, nothing more shows up

**Comment by hawolt** [comment] 2022-11-26 19:21
this is fixed in release 1.110 and was caused by the launch region being ignored

**Closed** 2022-11-26 19:21 UTC
